### ISSUE TITLE
Dictionary use

### ISSUE THREAD

**Issue by clemsciences** [GreekFellows/lesser-dannatt#1]
Hey,

I made Zoëga's dictionary available at https://github.com/cltk/old_norse_dictionary_zoega. Dictionary entries are accessible by using cltk module.

Is there a problem to have used your data?

**Comment by clemsciences** [comment]
Obviously, I read it:

`The dictionary data are from a digitized version of Geir Tómasson Zoëga's A Concise Dictionary of Old Icelandic, kindly provided by Tim Ermolaev (stridmann at gmail dot com).`

But what does it imply?

**Comment by ikazos** [comment]
I should have provided a license. I believe Tim is fine with reusing his data but it wouldn't hurt to ask him in an email.

**Comment by clemsciences** [comment]
I got a response from Tim Ermolaev and he lets me use the data and he just suggests to show this web site http://norroen.info/dct/zoega in docs.
